apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: k8s-test-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8s-test-microservice
spec:
  replicas: 5 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: k8s-test-microservice
    spec:
      containers:
      - name: k8s-test-microservice
        image: rilleralle/k8s-test-microservice-arm64
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /liveness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1